title: Scam Review Hub
description: Verify Website Legitimacy with Expert Analysis
url: "https://itisuniqueofficial.github.io/fay"
baseurl: "/fay"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
collections:
  reviews:
    output: true
    permalink: /reviews/:path
