title: Scam Review Hub
description: Verify Website Legitimacy with Expert Analysis
url: "http://fay.itisuniqueofficial.com"
baseurl: ""
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
collections:
  reviews:
    output: true
    permalink: /:path
